import { writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import type { ReductionResult } from "./types.js";
import { formatBytes, writeJsonAtomic } from "./utils.js";

export async function writeReports(
  result: ReductionResult,
  packageManager: { name: string; installCommand: string[] },
): Promise<void> {
  const markdown = `# Minimal reproduction

Generated by [BugBonsai](https://github.com/bugbonsai/bugbonsai).

## Failure

${result.finalSignature.errorName ?? "Command failure"}${result.finalSignature.primaryMessage ? `: ${result.finalSignature.primaryMessage}` : ""}

## Environment

- Operating system: ${os.platform()} ${os.release()}
- Architecture: ${os.arch()}
- Node: ${process.version}
- Package manager: ${packageManager.name}

## Install

\`\`\`bash
${packageManager.installCommand.join(" ")}
\`\`\`

## Reproduce

\`\`\`bash
${result.command.join(" ")}
\`\`\`

## Expected result

The command fails with the failure described above.

## Reduction

| Metric | Original | Reproduction |
| --- | ---: | ---: |
| Project files | ${result.originalMetrics.files} | ${result.finalMetrics.files} |
| Dependencies | ${result.originalMetrics.dependencies} | ${result.finalMetrics.dependencies} |
| Size | ${formatBytes(result.originalMetrics.bytes)} | ${formatBytes(result.finalMetrics.bytes)} |

- Candidate executions: ${result.candidateRuns}
- Accepted transformations: ${result.attempts.filter((attempt) => attempt.accepted).length}
- Duration: ${(result.durationMs / 1000).toFixed(1)} seconds

Generated BugBonsai report files are excluded from the project-file and size metrics.

## Notes

${result.portabilityFindings.length === 0 ? "No obvious portability problems were detected." : result.portabilityFindings.map((finding) => `- ${finding.path ? `${finding.path}: ` : ""}${finding.message}`).join("\n")}

BugBonsai uses heuristic failure matching and secret detection. Review the reproduction before sharing it publicly.
`;
  await writeFile(path.join(result.outputDirectory, "BUGBONSAI.md"), markdown);
  await writeJsonAtomic(
    path.join(result.outputDirectory, "bugbonsai-report.json"),
    {
      schemaVersion: 1,
      bugBonsaiVersion: "0.1.0",
      runId: result.runId,
      command: result.command,
      baseline: result.baseline,
      finalSignature: result.finalSignature,
      originalMetrics: result.originalMetrics,
      finalMetrics: result.finalMetrics,
      candidateRuns: result.candidateRuns,
      acceptedMutations: result.attempts.filter((attempt) => attempt.accepted),
      rejectedAttemptCount: result.attempts.filter(
        (attempt) => !attempt.accepted,
      ).length,
      durationMs: result.durationMs,
      portabilityFindings: result.portabilityFindings,
      security: {
        findings: result.securityFindings,
        disclaimer:
          "Heuristic secret scanning cannot guarantee that every secret was detected.",
      },
    },
  );
}
