import { writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import type { ReductionResult } from "./types.js";
import { formatBytes, writeJsonAtomic } from "./utils.js";
import { VERSION } from "./version.js";

export async function writeReports(
  result: ReductionResult,
  packageManager: {
    name: string;
    installCommand: string[];
    lockfiles: string[];
    workspaceType: string;
    warnings: string[];
  },
  options: { noInstall: boolean },
): Promise<void> {
  const markdown = `# Minimal reproduction

Generated by [BugBonsai](https://github.com/bugbonsai/bugbonsai).

## Failure

${result.finalSignature.errorName ?? "Command failure"}${result.finalSignature.primaryMessage ? `: ${result.finalSignature.primaryMessage}` : ""}

## Environment

- Operating system: ${os.platform()} ${os.release()}
- Architecture: ${os.arch()}
- Node: ${process.version}
- Package manager: ${packageManager.name}
- Workspace: ${packageManager.workspaceType}

## Install

${options.noInstall ? "No dependency installation was requested." : `\`\`\`bash\n${packageManager.installCommand.join(" ")}\n\`\`\``}

## Reproduce

\`\`\`bash
${result.invocationDirectory ? `cd ${result.invocationDirectory}\n` : ""}${result.command.join(" ")}
\`\`\`

## Expected result

The command fails with the failure described above.

## Reduction

| Metric | Original | Reproduction |
| --- | ---: | ---: |
| Project files | ${result.originalMetrics.files} | ${result.finalMetrics.files} |
| Dependencies | ${result.originalMetrics.dependencies} | ${result.finalMetrics.dependencies} |
| Size | ${formatBytes(result.originalMetrics.bytes)} | ${formatBytes(result.finalMetrics.bytes)} |

- Candidate executions: ${result.candidateRuns}
- Cached candidate rejections: ${result.cacheHits}
- Dependency snapshots reused: ${result.attempts.filter((attempt) => attempt.dependencySnapshotReused).length}
- Accepted transformations: ${result.attempts.filter((attempt) => attempt.accepted).length}
- Duration: ${(result.durationMs / 1000).toFixed(1)} seconds

Generated BugBonsai report files are excluded from the project-file and size metrics.

## Notes

${[...(result.portabilityFindings.length === 0 ? ["No obvious portability problems were detected."] : result.portabilityFindings.map((finding) => `- ${finding.path ? `${finding.path}: ` : ""}${finding.message}`)), ...packageManager.warnings.map((warning) => `- Package manager: ${warning}`)].join("\n")}

Detected adapters: ${result.detectedAdapters.length > 0 ? result.detectedAdapters.join(", ") : "generic"}.

BugBonsai uses heuristic failure matching and secret detection. Review the reproduction before sharing it publicly.
`;
  await writeFile(path.join(result.outputDirectory, "BUGBONSAI.md"), markdown);
  await writeJsonAtomic(
    path.join(result.outputDirectory, "bugbonsai-report.json"),
    {
      schemaVersion: 1,
      bugBonsaiVersion: VERSION,
      runId: result.runId,
      command: result.command,
      installCommand: options.noInstall ? null : packageManager.installCommand,
      invocationDirectory: result.invocationDirectory,
      detectedAdapters: result.detectedAdapters,
      packageManager: {
        name: packageManager.name,
        workspaceType: packageManager.workspaceType,
        lockfiles: packageManager.lockfiles,
        warnings: packageManager.warnings,
      },
      baseline: result.baseline,
      finalSignature: result.finalSignature,
      originalMetrics: result.originalMetrics,
      finalMetrics: result.finalMetrics,
      candidateRuns: result.candidateRuns,
      cacheHits: result.cacheHits,
      dependencySnapshotsReused: result.attempts.filter(
        (attempt) => attempt.dependencySnapshotReused,
      ).length,
      acceptedMutations: result.attempts.filter((attempt) => attempt.accepted),
      rejectedAttemptCount: result.attempts.filter(
        (attempt) => !attempt.accepted,
      ).length,
      durationMs: result.durationMs,
      portabilityFindings: result.portabilityFindings,
      security: {
        findings: result.securityFindings,
        disclaimer:
          "Heuristic secret scanning cannot guarantee that every secret was detected.",
      },
    },
  );
}
